# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jLI01xcH88FEe_fTIVho9HcFas9132a
"""

from transformers import pipeline

# Set up the model pipeline using Hugging Face's GPT model
generator = pipeline("text-generation", model="EleutherAI/gpt-neo-2.7B")  # You can also use GPT-2 or other models

# Step 1: Generate a creative writing prompt based on user input
def generate_story_prompt(genre, character, setting):
    prompt = f"Write a {genre} story about {character} who embarks on an adventure in {setting}."
    return prompt

# Step 2: Use Hugging Face's pipeline to generate the first part of the story
def generate_story(prompt):
    story = generator(prompt, max_length=250, num_return_sequences=1, temperature=0.7)
    return story[0]['generated_text']

# Example usage
def create_story(genre, character, setting):
    prompt = generate_story_prompt(genre, character, setting)
    print(f"Generated Story Prompt: {prompt}\n")

    story = generate_story(prompt)
    print(f"Generated Story: \n{story}")

# User input
genre = "fantasy"
character = "a young wizard"
setting = "a magical forest"

# Generate the story
create_story(genre, character, setting)

pip install transformers
pip install torch  # If you don't have PyTorch installed yet

pip install transformers
pip install torch  # If you don't have PyTorch installed yet